export type Lang = "en"|"hi"|"te"|"ta"|"kn"|"mr"|"bn"|"gu";
export const languages: {code:Lang; label:string}[] = [
  {code:"en",label:"English"},{code:"hi",label:"हिन्दी"},{code:"te",label:"తెలుగు"},
  {code:"ta",label:"தமிழ்"},{code:"kn",label:"ಕನ್ನಡ"},{code:"mr",label:"मराठी"},
  {code:"bn",label:"বাংলা"},{code:"gu",label:"ગુજરાતી"}
];

export const t: Record<Lang, Record<string,string>> = {
  en:{
    home:"Home", search:"Standards Search", analysis:"Product Analysis", tender:"Tender Analysis",
    explorer:"Standards Explorer", compare:"Compare Products", recommend:"Recommendation",
    safety:"Safety & Buying", evidence:"Evidence Center", dashboard:"Dashboard", settings:"Settings",
    hero:"Understand requirements. Find standards. Buy with confidence.",
    heroSub:"BIS SENSOR turns technical procurement language into clear standards, compliance and decision support — with evidence shown alongside AI analysis.",
    searchPlaceholder:"Describe a product, tender requirement or question…",
    analyze:"Analyze requirements", upload:"Upload tender", voice:"Voice search",
    example:"Example", official:"Official information", ai:"AI analysis", thirdParty:"Third-party", unverified:"Unverified",
    applicable:"Applicable standards", related:"Related standards", missing:"Missing information",
    confidence:"AI Recommendation Confidence", score:"AI-Assisted Standards-Based Score",
    simple:"Explain Simply", why:"Why this standard matters", safetyIntro:"This section helps you check safety and procurement essentials before relying on a product or standard recommendation.",
    buyingIntro:"Use this checklist as a practical pre-purchase guide. It does not replace official standards, laws, certification authorities or professional judgement.",
    level:"Quality level", compareNow:"Compare selected", noData:"No verified applicable standard found.", selectRequired:"A few details are missing. Select what you need so the recommendation can be more precise.",
    source:"Evidence / source", verify:"Verification required", details:"View details", budget:"Budget", useCase:"Intended use",
    environment:"Environment", safetyPriority:"Safety priority", quality:"Preferred quality level", generate:"Generate recommendation",
    best:"Best overall", value:"Best value", budgetChoice:"Budget choice", pros:"Pros", cons:"Cons", checklist:"Buying checklist",
    disclaimer:"BIS SENSOR provides AI-assisted recommendations and decision support. It does not replace official BIS publications, laws, regulations, certification authorities, procurement rules, or professional technical judgement. Verify critical requirements against authoritative sources before procurement.",
    officialSource:"Official BIS sources",
  },
  hi:{
    home:"होम",search:"मानक खोज",analysis:"उत्पाद विश्लेषण",tender:"टेंडर विश्लेषण",explorer:"मानक एक्सप्लोरर",compare:"उत्पाद तुलना",recommend:"सिफारिश",safety:"सुरक्षा और खरीद",evidence:"साक्ष्य केंद्र",dashboard:"डैशबोर्ड",settings:"सेटिंग्स",
    hero:"आवश्यकताएँ समझें। मानक खोजें। बेहतर निर्णय लें।",heroSub:"BIS SENSOR तकनीकी खरीद भाषा को स्पष्ट मानकों, अनुपालन और निर्णय सहायता में बदलता है।",
    searchPlaceholder:"उत्पाद, टेंडर आवश्यकता या प्रश्न लिखें…",analyze:"आवश्यकताओं का विश्लेषण",upload:"टेंडर अपलोड",voice:"वॉइस खोज",example:"Example",official:"आधिकारिक जानकारी",ai:"AI विश्लेषण",thirdParty:"थर्ड-पार्टी",unverified:"असत्यापित",
    applicable:"लागू मानक",related:"संबंधित मानक",missing:"अपूर्ण जानकारी",confidence:"AI सिफारिश विश्वास",score:"AI-सहायित मानक-आधारित स्कोर",simple:"सरल समझ",why:"यह मानक क्यों महत्वपूर्ण है",safetyIntro:"यह भाग खरीद से पहले सुरक्षा और आवश्यक जाँच समझने में मदद करता है।",buyingIntro:"यह एक व्यावहारिक खरीद चेकलिस्ट है। यह आधिकारिक मानकों या कानून का स्थान नहीं लेती।",level:"गुणवत्ता स्तर",compareNow:"चयनित की तुलना",noData:"कोई सत्यापित लागू मानक नहीं मिला।",selectRequired:"कुछ जानकारी अधूरी है। अधिक सटीक सिफारिश के लिए विकल्प चुनें।",source:"साक्ष्य / स्रोत",verify:"सत्यापन आवश्यक",details:"विवरण देखें",budget:"बजट",useCase:"उपयोग",environment:"पर्यावरण",safetyPriority:"सुरक्षा प्राथमिकता",quality:"पसंदीदा गुणवत्ता स्तर",generate:"सिफारिश बनाएँ",best:"सर्वश्रेष्ठ",value:"सर्वोत्तम मूल्य",budgetChoice:"बजट विकल्प",pros:"फायदे",cons:"कमियाँ",checklist:"खरीद चेकलिस्ट",disclaimer:"BIS SENSOR AI-सहायित निर्णय समर्थन देता है। महत्वपूर्ण आवश्यकताओं को खरीद से पहले आधिकारिक स्रोतों से सत्यापित करें।",officialSource:"Official BIS sources",
  },
  te:{
    home:"హోమ్",search:"ప్రమాణాల శోధన",analysis:"ఉత్పత్తి విశ్లేషణ",tender:"టెండర్ విశ్లేషణ",explorer:"ప్రమాణాల ఎక్స్‌ప్లోరర్",compare:"ఉత్పత్తుల పోలిక",recommend:"సిఫార్సు",safety:"భద్రత & కొనుగోలు",evidence:"సాక్ష్య కేంద్రం",dashboard:"డాష్‌బోర్డ్",settings:"సెట్టింగ్స్",
    hero:"అవసరాలను అర్థం చేసుకోండి. ప్రమాణాలను కనుగొనండి. మెరుగైన నిర్ణయం తీసుకోండి.",heroSub:"BIS SENSOR సాంకేతిక కొనుగోలు అవసరాలను సులభమైన ప్రమాణాలు, అనుగుణ్యత మరియు నిర్ణయ సహాయంగా మార్చుతుంది.",
    searchPlaceholder:"ఉత్పత్తి, టెండర్ అవసరం లేదా ప్రశ్నను నమోదు చేయండి…",analyze:"అవసరాలను విశ్లేషించు",upload:"టెండర్ అప్లోడ్",voice:"వాయిస్ శోధన",example:"Example",official:"అధికారిక సమాచారం",ai:"AI విశ్లేషణ",thirdParty:"మూడవ పక్షం",unverified:"ధృవీకరించలేదు",
    applicable:"వర్తించే ప్రమాణాలు",related:"సంబంధిత ప్రమాణాలు",missing:"అసంపూర్ణ సమాచారం",confidence:"AI సిఫార్సు నమ్మకం",score:"AI-సహాయంతో ప్రమాణ ఆధారిత స్కోర్",simple:"సులభంగా వివరించు",why:"ఈ ప్రమాణం ఎందుకు ముఖ్యం",safetyIntro:"కొనుగోలు ముందు భద్రత మరియు అవసరమైన తనిఖీలను అర్థం చేసుకోవడానికి ఈ విభాగం సహాయపడుతుంది.",buyingIntro:"ఇది ప్రీ-పర్చేజ్ చెక్‌లిస్ట్. అధికారిక ప్రమాణాలు లేదా చట్టాలకు ఇది ప్రత్యామ్నాయం కాదు.",level:"నాణ్యత స్థాయి",compareNow:"ఎంచుకున్న వాటిని పోల్చు",noData:"ధృవీకరించిన వర్తించే ప్రమాణం కనబడలేదు.",selectRequired:"కొంత సమాచారం లేదు. సిఫార్సును మెరుగుపరచడానికి ఎంపికలను ఎంచుకోండి.",source:"సాక్ష్యం / మూలం",verify:"ధృవీకరణ అవసరం",details:"వివరాలు",budget:"బడ్జెట్",useCase:"వినియోగం",environment:"పరిసరాలు",safetyPriority:"భద్రత ప్రాధాన్యత",quality:"నాణ్యత స్థాయి",generate:"సిఫార్సు తయారు చేయి",best:"ఉత్తమ ఎంపిక",value:"ఉత్తమ విలువ",budgetChoice:"బడ్జెట్ ఎంపిక",pros:"ప్రయోజనాలు",cons:"లోపాలు",checklist:"కొనుగోలు చెక్‌లిస్ట్",disclaimer:"BIS SENSOR AI ఆధారిత నిర్ణయ సహాయం మాత్రమే అందిస్తుంది. ముఖ్యమైన అవసరాలను కొనుగోలు ముందు అధికారిక మూలాల ద్వారా ధృవీకరించండి.",officialSource:"Official BIS sources",
  },
  ta:{home:"முகப்பு",search:"தரநிலை தேடல்",analysis:"தயாரிப்பு பகுப்பாய்வு",tender:"டெண்டர் பகுப்பாய்வு",explorer:"தரநிலை எக்ஸ்ப்ளோரர்",compare:"தயாரிப்பு ஒப்பீடு",recommend:"பரிந்துரை",safety:"பாதுகாப்பு & கொள்முதல்",evidence:"ஆதார மையம்",dashboard:"டாஷ்போர்டு",settings:"அமைப்புகள்",hero:"தேவைகளை புரிந்துகொள்ளுங்கள். தரநிலைகளை கண்டுபிடியுங்கள். சிறந்த முடிவு எடுங்கள்.",heroSub:"BIS SENSOR தொழில்நுட்ப கொள்முதல் தேவைகளை தெளிவான தரநிலைகள் மற்றும் முடிவு உதவியாக மாற்றுகிறது.",searchPlaceholder:"தயாரிப்பு, டெண்டர் தேவை அல்லது கேள்வியை உள்ளிடவும்…",analyze:"தேவைகளை பகுப்பாய்வு செய்",upload:"டெண்டரை பதிவேற்று",voice:"குரல் தேடல்",example:"Example",official:"அதிகாரப்பூர்வ தகவல்",ai:"AI பகுப்பாய்வு",thirdParty:"மூன்றாம் தரப்பு",unverified:"சரிபார்க்கப்படவில்லை",applicable:"பொருந்தும் தரநிலைகள்",related:"தொடர்புடைய தரநிலைகள்",missing:"காணாமல் போன தகவல்",confidence:"AI பரிந்துரை நம்பிக்கை",score:"AI உதவிய தரநிலை அடிப்படையிலான மதிப்பெண்",simple:"எளிமையாக விளக்கு",why:"இந்த தரநிலை ஏன் முக்கியம்",safetyIntro:"கொள்முதல் முன் பாதுகாப்பு மற்றும் தேவையான சரிபார்ப்புகளை புரிந்துகொள்ள இந்த பகுதி உதவுகிறது.",buyingIntro:"இது நடைமுறை கொள்முதல் சரிபார்ப்பு பட்டியல்; அதிகாரப்பூர்வ தரநிலைகளுக்கு மாற்றாகாது.",level:"தர நிலை",compareNow:"தேர்ந்தெடுத்ததை ஒப்பிடு",noData:"சரிபார்க்கப்பட்ட பொருந்தும் தரநிலை இல்லை.",selectRequired:"சில தகவல்கள் இல்லை. பரிந்துரையை மேம்படுத்த ஒரு விருப்பத்தைத் தேர்ந்தெடுக்கவும்.",source:"ஆதாரம்",verify:"சரிபார்ப்பு தேவை",details:"விவரங்கள்",budget:"பட்ஜெட்",useCase:"பயன்பாடு",environment:"சூழல்",safetyPriority:"பாதுகாப்பு முன்னுரிமை",quality:"விரும்பிய தர நிலை",generate:"பரிந்துரை உருவாக்கு",best:"சிறந்த தேர்வு",value:"சிறந்த மதிப்பு",budgetChoice:"பட்ஜெட் தேர்வு",pros:"நன்மைகள்",cons:"குறைபாடுகள்",checklist:"கொள்முதல் சரிபார்ப்பு",disclaimer:"BIS SENSOR AI உதவியுடன் முடிவு ஆதரவை வழங்குகிறது. முக்கிய தேவைகளை அதிகாரப்பூர்வ மூலங்களில் சரிபார்க்கவும்.",officialSource:"Official BIS sources",},
  kn:{home:"ಮುಖಪುಟ",search:"ಮಾನದಂಡ ಹುಡುಕಾಟ",analysis:"ಉತ್ಪನ್ನ ವಿಶ್ಲೇಷಣೆ",tender:"ಟೆಂಡರ್ ವಿಶ್ಲೇಷಣೆ",explorer:"ಮಾನದಂಡ ಎಕ್ಸ್‌ಪ್ಲೋರರ್",compare:"ಉತ್ಪನ್ನ ಹೋಲಿಕೆ",recommend:"ಶಿಫಾರಸು",safety:"ಸುರಕ್ಷತೆ & ಖರೀದಿ",evidence:"ಸಾಕ್ಷ್ಯ ಕೇಂದ್ರ",dashboard:"ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",settings:"ಸೆಟ್ಟಿಂಗ್ಸ್",hero:"ಅವಶ್ಯಕತೆಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ. ಮಾನದಂಡಗಳನ್ನು ಕಂಡುಹಿಡಿಯಿರಿ. ಉತ್ತಮ ನಿರ್ಧಾರ ತೆಗೆದುಕೊಳ್ಳಿ.",heroSub:"BIS SENSOR ತಾಂತ್ರಿಕ ಖರೀದಿ ಅಗತ್ಯಗಳನ್ನು ಸ್ಪಷ್ಟ ಮಾನದಂಡ ಮತ್ತು ನಿರ್ಧಾರ ಸಹಾಯವಾಗಿ ಪರಿವರ್ತಿಸುತ್ತದೆ.",searchPlaceholder:"ಉತ್ಪನ್ನ, ಟೆಂಡರ್ ಅವಶ್ಯಕತೆ ಅಥವಾ ಪ್ರಶ್ನೆಯನ್ನು ನಮೂದಿಸಿ…",analyze:"ಅವಶ್ಯಕತೆ ವಿಶ್ಲೇಷಿಸಿ",upload:"ಟೆಂಡರ್ ಅಪ್‌ಲೋಡ್",voice:"ಧ್ವನಿ ಹುಡುಕಾಟ",example:"Example",official:"ಅಧಿಕೃತ ಮಾಹಿತಿ",ai:"AI ವಿಶ್ಲೇಷಣೆ",thirdParty:"ಮೂರನೇ ಪಕ್ಷ",unverified:"ಪರಿಶೀಲಿಸಿಲ್ಲ",applicable:"ಅನ್ವಯಿಸುವ ಮಾನದಂಡಗಳು",related:"ಸಂಬಂಧಿತ ಮಾನದಂಡಗಳು",missing:"ಕಾಣೆಯಾದ ಮಾಹಿತಿ",confidence:"AI ಶಿಫಾರಸು ವಿಶ್ವಾಸ",score:"AI ಸಹಾಯಿತ ಮಾನದಂಡ ಸ್ಕೋರ್",simple:"ಸರಳವಾಗಿ ವಿವರಿಸಿ",why:"ಈ ಮಾನದಂಡ ಏಕೆ ಮುಖ್ಯ",safetyIntro:"ಖರೀದಿಗೆ ಮೊದಲು ಸುರಕ್ಷತೆ ಮತ್ತು ಅಗತ್ಯ ಪರಿಶೀಲನೆಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ಈ ವಿಭಾಗ ಸಹಾಯ ಮಾಡುತ್ತದೆ.",buyingIntro:"ಇದು ಪ್ರಾಯೋಗಿಕ ಖರೀದಿ ಪರಿಶೀಲನಾ ಪಟ್ಟಿ; ಅಧಿಕೃತ ಮಾನದಂಡಗಳಿಗೆ ಪರ್ಯಾಯವಲ್ಲ.",level:"ಗುಣಮಟ್ಟ ಮಟ್ಟ",compareNow:"ಆಯ್ದವುಗಳನ್ನು ಹೋಲಿಸಿ",noData:"ಪರಿಶೀಲಿಸಿದ ಅನ್ವಯಿಸುವ ಮಾನದಂಡ ಸಿಗಲಿಲ್ಲ.",selectRequired:"ಕೆಲವು ಮಾಹಿತಿ ಇಲ್ಲ. ಶಿಫಾರಸನ್ನು ಉತ್ತಮಗೊಳಿಸಲು ಆಯ್ಕೆ ಮಾಡಿ.",source:"ಸಾಕ್ಷ್ಯ",verify:"ಪರಿಶೀಲನೆ ಅಗತ್ಯ",details:"ವಿವರಗಳು",budget:"ಬಜೆಟ್",useCase:"ಬಳಕೆ",environment:"ಪರಿಸರ",safetyPriority:"ಸುರಕ್ಷತಾ ಆದ್ಯತೆ",quality:"ಗುಣಮಟ್ಟ ಮಟ್ಟ",generate:"ಶಿಫಾರಸು ರಚಿಸಿ",best:"ಅತ್ಯುತ್ತಮ",value:"ಅತ್ಯುತ್ತಮ ಮೌಲ್ಯ",budgetChoice:"ಬಜೆಟ್ ಆಯ್ಕೆ",pros:"ಲಾಭಗಳು",cons:"ಅಪಾಯಗಳು",checklist:"ಖರೀದಿ ಪರಿಶೀಲನೆ",disclaimer:"BIS SENSOR AI ಸಹಾಯಿತ ನಿರ್ಧಾರ ಬೆಂಬಲ ನೀಡುತ್ತದೆ. ಮುಖ್ಯ ಅವಶ್ಯಕತೆಗಳನ್ನು ಅಧಿಕೃತ ಮೂಲಗಳಿಂದ ಪರಿಶೀಲಿಸಿ.",officialSource:"Official BIS sources",},
  mr:{home:"मुख्यपृष्ठ",search:"मानक शोध",analysis:"उत्पादन विश्लेषण",tender:"टेंडर विश्लेषण",explorer:"मानक एक्सप्लोरर",compare:"उत्पादन तुलना",recommend:"शिफारस",safety:"सुरक्षा आणि खरेदी",evidence:"पुरावा केंद्र",dashboard:"डॅशबोर्ड",settings:"सेटिंग्ज",hero:"गरजा समजा. मानके शोधा. चांगला निर्णय घ्या.",heroSub:"BIS SENSOR तांत्रिक खरेदी गरजा स्पष्ट मानके आणि निर्णय सहाय्यात रूपांतरित करते.",searchPlaceholder:"उत्पादन, टेंडर गरज किंवा प्रश्न लिहा…",analyze:"गरजांचे विश्लेषण",upload:"टेंडर अपलोड",voice:"व्हॉइस शोध",example:"Example",official:"अधिकृत माहिती",ai:"AI विश्लेषण",thirdParty:"तृतीय पक्ष",unverified:"असत्यापित",applicable:"लागू मानके",related:"संबंधित मानके",missing:"अपूर्ण माहिती",confidence:"AI शिफारस विश्वास",score:"AI-सहाय्यित मानक स्कोअर",simple:"सोपे स्पष्टीकरण",why:"हे मानक का महत्त्वाचे आहे",safetyIntro:"खरेदीपूर्वी सुरक्षा आणि आवश्यक तपासणी समजण्यासाठी हा विभाग मदत करतो.",buyingIntro:"ही व्यावहारिक खरेदी तपासणी यादी आहे; अधिकृत मानकांचा पर्याय नाही.",level:"गुणवत्ता स्तर",compareNow:"निवडलेल्यांची तुलना",noData:"सत्यापित लागू मानक सापडले नाही.",selectRequired:"काही माहिती अपूर्ण आहे. अधिक अचूक शिफारसीसाठी पर्याय निवडा.",source:"पुरावा / स्रोत",verify:"तपासणी आवश्यक",details:"तपशील",budget:"अर्थसंकल्प",useCase:"वापर",environment:"परिसर",safetyPriority:"सुरक्षा प्राधान्य",quality:"पसंतीचा गुणवत्ता स्तर",generate:"शिफारस तयार करा",best:"सर्वोत्तम",value:"सर्वोत्तम मूल्य",budgetChoice:"बजेट पर्याय",pros:"फायदे",cons:"तोटे",checklist:"खरेदी तपासणी",disclaimer:"BIS SENSOR AI-सहाय्यित निर्णय समर्थन देते. महत्त्वाच्या गरजा अधिकृत स्रोतांद्वारे तपासा.",officialSource:"Official BIS sources",},
  bn:{home:"হোম",search:"মান অনুসন্ধান",analysis:"পণ্য বিশ্লেষণ",tender:"টেন্ডার বিশ্লেষণ",explorer:"মান এক্সপ্লোরার",compare:"পণ্য তুলনা",recommend:"সুপারিশ",safety:"নিরাপত্তা ও ক্রয়",evidence:"প্রমাণ কেন্দ্র",dashboard:"ড্যাশবোর্ড",settings:"সেটিংস",hero:"প্রয়োজন বুঝুন। মান খুঁজুন। ভালো সিদ্ধান্ত নিন।",heroSub:"BIS SENSOR প্রযুক্তিগত ক্রয় প্রয়োজনকে পরিষ্কার মান, সম্মতি এবং সিদ্ধান্ত সহায়তায় রূপান্তর করে।",searchPlaceholder:"পণ্য, টেন্ডার প্রয়োজন বা প্রশ্ন লিখুন…",analyze:"প্রয়োজন বিশ্লেষণ",upload:"টেন্ডার আপলোড",voice:"ভয়েস অনুসন্ধান",example:"Example",official:"সরকারি তথ্য",ai:"AI বিশ্লেষণ",thirdParty:"তৃতীয় পক্ষ",unverified:"যাচাই হয়নি",applicable:"প্রযোজ্য মান",related:"সম্পর্কিত মান",missing:"অনুপস্থিত তথ্য",confidence:"AI সুপারিশ আস্থা",score:"AI-সহায়িত মানভিত্তিক স্কোর",simple:"সহজ করে বলুন",why:"এই মান কেন গুরুত্বপূর্ণ",safetyIntro:"ক্রয়ের আগে নিরাপত্তা ও প্রয়োজনীয় যাচাই বুঝতে এই বিভাগ সাহায্য করে।",buyingIntro:"এটি একটি ব্যবহারিক ক্রয় চেকলিস্ট; সরকারি মানের বিকল্প নয়।",level:"মানের স্তর",compareNow:"নির্বাচিত তুলনা",noData:"কোনও যাচাইকৃত প্রযোজ্য মান পাওয়া যায়নি।",selectRequired:"কিছু তথ্য অসম্পূর্ণ। আরও নির্ভুল সুপারিশের জন্য বিকল্প বেছে নিন।",source:"প্রমাণ / উৎস",verify:"যাচাই প্রয়োজন",details:"বিস্তারিত",budget:"বাজেট",useCase:"ব্যবহার",environment:"পরিবেশ",safetyPriority:"নিরাপত্তা অগ্রাধিকার",quality:"পছন্দের মানের স্তর",generate:"সুপারিশ তৈরি করুন",best:"সেরা",value:"সেরা মূল্য",budgetChoice:"বাজেট পছন্দ",pros:"সুবিধা",cons:"অসুবিধা",checklist:"ক্রয় চেকলিস্ট",disclaimer:"BIS SENSOR AI-সহায়িত সিদ্ধান্ত সহায়তা দেয়। গুরুত্বপূর্ণ প্রয়োজন সরকারি উৎস থেকে যাচাই করুন।",officialSource:"Official BIS sources",},
  gu:{home:"હોમ",search:"ધોરણ શોધ",analysis:"ઉત્પાદન વિશ્લેષણ",tender:"ટેન્ડર વિશ્લેષણ",explorer:"ધોરણ એક્સપ્લોરર",compare:"ઉત્પાદન સરખામણી",recommend:"ભલામણ",safety:"સુરક્ષા અને ખરીદી",evidence:"પુરાવા કેન્દ્ર",dashboard:"ડેશબોર્ડ",settings:"સેટિંગ્સ",hero:"જરૂરિયાત સમજો. ધોરણ શોધો. વધુ સારું નિર્ણય લો.",heroSub:"BIS SENSOR ટેકનિકલ ખરીદી જરૂરિયાતોને સ્પષ્ટ ધોરણો અને નિર્ણય સહાયમાં ફેરવે છે.",searchPlaceholder:"ઉત્પાદન, ટેન્ડર જરૂરિયાત અથવા પ્રશ્ન લખો…",analyze:"જરૂરિયાત વિશ્લેષણ",upload:"ટેન્ડર અપલોડ",voice:"વૉઇસ શોધ",example:"Example",official:"અધિકૃત માહિતી",ai:"AI વિશ્લેષણ",thirdParty:"તૃતીય પક્ષ",unverified:"ચકાસાયેલ નથી",applicable:"લાગુ ધોરણો",related:"સંબંધિત ધોરણો",missing:"અપૂર્ણ માહિતી",confidence:"AI ભલામણ વિશ્વાસ",score:"AI-સહાયિત ધોરણ આધારિત સ્કોર",simple:"સરળ સમજાવો",why:"આ ધોરણ શા માટે મહત્વનું છે",safetyIntro:"ખરીદી પહેલાં સુરક્ષા અને જરૂરી ચકાસણીઓ સમજવામાં આ વિભાગ મદદ કરે છે.",buyingIntro:"આ વ્યવહારુ ખરીદી ચેકલિસ્ટ છે; અધિકૃત ધોરણોનો વિકલ્પ નથી.",level:"ગુણવત્તા સ્તર",compareNow:"પસંદ કરેલ સરખાવો",noData:"કોઈ ચકાસાયેલ લાગુ ધોરણ મળ્યું નથી.",selectRequired:"કેટલીક માહિતી અધૂરી છે. વધુ ચોક્કસ ભલામણ માટે વિકલ્પ પસંદ કરો.",source:"પુરાવો / સ્ત્રોત",verify:"ચકાસણી જરૂરી",details:"વિગતો",budget:"બજેટ",useCase:"ઉપયોગ",environment:"પર્યાવરણ",safetyPriority:"સુરક્ષા પ્રાથમિકતા",quality:"પસંદ ગુણવત્તા સ્તર",generate:"ભલામણ બનાવો",best:"શ્રેષ્ઠ",value:"શ્રેષ્ઠ મૂલ્ય",budgetChoice:"બજેટ વિકલ્પ",pros:"ફાયદા",cons:"ઓછતા",checklist:"ખરીદી ચેકલિસ્ટ",disclaimer:"BIS SENSOR AI-સહાયિત નિર્ણય સપોર્ટ આપે છે. મહત્વપૂર્ણ જરૂરિયાતો અધિકૃત સ્ત્રોતોથી ચકાસો.",officialSource:"Official BIS sources",}
};

export function tx(lang:Lang,key:string){ return t[lang][key] ?? t.en[key] ?? key; }
